export default function Exersices06() {
  return (
    <div>
        <div className="w-[500px] h-[200px] overflow-auto">
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Harum, numquam voluptatem quis culpa voluptas maiores qui architecto, velit voluptates at incidunt, nam quas. Rem quam laudantium, iste suscipit blanditiis amet.
            Consequatur officia porro quae suscipit non asperiores obcaecati voluptatibus quaerat iste natus, eligendi corporis qui commodi reiciendis accusantium magnam perspiciatis quisquam sint illo. Perspiciatis, nisi porro minus animi quia ratione?
            Consequatur sit, minus in libero temporibus distinctio dolorum dolores fugiat totam iure. Velit, similique. Cumque officiis rerum eaque illum obcaecati eos dignissimos adipisci nemo numquam enim aperiam doloremque, perferendis magni?
            Suscipit, temporibus labore nobis hic animi impedit sunt ut, similique quae praesentium at aut. Excepturi eius consectetur ea eaque sint ipsum dolor ducimus, nobis et, aut consequuntur eveniet atque blanditiis.
            Deserunt veritatis ea vero assumenda saepe est eveniet asperiores explicabo recusandae nihil aperiam laudantium qui, itaque, quidem quas ipsum! Vero animi corrupti commodi dignissimos error maxime obcaecati non esse consequatur?
            Tempora ducimus natus fugiat eum, necessitatibus architecto a reiciendis distinctio. Facere consectetur amet incidunt, placeat tempora nulla quisquam, corrupti cumque magnam laboriosam quidem at pariatur ipsum necessitatibus nemo minima sunt.
            Possimus doloremque iste minus eveniet itaque nam eius vitae temporibus ea ipsum aliquam magni vel dolores perferendis eum sit qui blanditiis a, necessitatibus accusamus error maiores eos. Vero, quisquam aspernatur!
            Autem accusantium necessitatibus, aperiam fuga, ex dolores voluptate illum dolorem quam sapiente, at cumque ab! Perspiciatis reiciendis molestias cupiditate numquam pariatur optio harum necessitatibus, omnis, quam assumenda vero praesentium sit.
            Aut nisi itaque consequatur alias soluta perferendis nemo cum minus numquam sequi voluptates, iure tenetur, qui veritatis, sint quasi aperiam. Quasi aspernatur dignissimos vero totam perferendis obcaecati nesciunt nostrum delectus.
            Quos modi fugiat vitae quo unde, deserunt adipisci eaque labore tempora id ipsa, saepe officiis aliquid esse doloremque non, delectus earum aut enim quasi dolorum sed. Dolorem odio dolorum libero!
            Tempora exercitationem temporibus deserunt illum vitae dignissimos error corporis porro cumque unde deleniti iusto ex in neque ipsa, molestiae mollitia fugiat? Accusamus libero beatae aliquid quaerat dolore maiores laborum esse.
            Magni, rerum porro? Modi, ea numquam nostrum maxime dolore similique, repellendus id, inventore optio eveniet sed ab fuga quod sequi deleniti ducimus fugiat rerum! Impedit commodi sequi blanditiis dolor debitis.
            Dolor voluptates illum quia id distinctio! Esse ratione cumque labore expedita ipsum? Iste laboriosam obcaecati vero distinctio magni! Est deleniti vero facilis quaerat reprehenderit earum! Harum maiores totam adipisci quo!
            Corporis dolor dolore dolorum quaerat numquam explicabo illo harum in, provident voluptatum omnis iste tenetur distinctio quae architecto tempore laborum repellat quasi impedit mollitia sunt id eius, qui officia? Animi!
            Et aperiam, libero quibusdam quia maiores ut culpa quas ad odit itaque nemo laboriosam voluptatum maxime reiciendis rerum minima distinctio eos, ipsam nostrum tempora. Cumque accusamus debitis aperiam tenetur. Possimus.
            Laudantium consequuntur odio cum pariatur quisquam dolor nemo est ratione a, quasi animi veritatis consequatur similique, explicabo maiores corrupti obcaecati hic dolorum dolore eligendi corporis? Illum assumenda mollitia quidem ducimus!
            Tempore, nobis! Quas distinctio aperiam assumenda iste rerum doloremque. Provident, deleniti, eos assumenda hic accusamus pariatur consequatur nobis dolor vel voluptatem earum sunt ad illum ullam beatae sit magni quam.
            Nemo dolorem dolores ullam unde incidunt accusantium earum cum quasi ratione minima labore perferendis culpa aperiam eum, facere dolor consectetur ducimus repudiandae sit saepe! Ipsam assumenda rem id accusamus cupiditate.
            Libero sit doloremque, cupiditate odit molestiae voluptatum iste cumque nihil eveniet error, reiciendis exercitationem rerum est corrupti magnam esse nesciunt. Eius hic incidunt pariatur fugiat qui accusamus unde suscipit quia?
            Odit provident tenetur omnis dolore assumenda architecto iste aliquid eius tempora minima veritatis fuga, totam sit laborum autem numquam suscipit, ducimus facilis reprehenderit ipsa doloribus, aperiam nihil nam! Nesciunt, autem.
            Impedit ducimus mollitia earum corporis molestiae esse quia libero. Omnis, eveniet, enim commodi totam illum dolore doloremque molestias dolor ad hic vel voluptates voluptate maiores? Laboriosam consequatur corporis nostrum eveniet?
            Harum quam maxime blanditiis quasi, asperiores necessitatibus rem, quos iste tempore nulla voluptatem enim obcaecati quo mollitia corporis soluta esse molestias. Minima pariatur doloremque, velit aut sint ad magnam quisquam?
            Quos vitae pariatur eligendi tempore aperiam quaerat! Nemo laudantium odit laborum fugiat ipsa quia distinctio illo fugit quo sit ea reprehenderit suscipit eligendi veniam esse iure ut perferendis, unde iste.
            Commodi deleniti quibusdam non accusamus unde, nesciunt numquam tempora minima fugit aut dignissimos itaque ad accusantium optio perferendis omnis dolorem veniam? Quisquam distinctio vitae minus voluptas maiores suscipit, at nisi.
            Fuga, dolores numquam. Nihil consectetur natus fuga ea minus in modi non aliquid itaque repudiandae voluptatem nulla tempore, aliquam necessitatibus, ipsum aperiam vitae quas voluptatum deserunt impedit iure, nesciunt neque!
            Et error reiciendis ex quisquam. Iste, aliquam accusamus quo rerum fugiat sit distinctio iure at temporibus sed voluptatibus! Impedit in quibusdam voluptates blanditiis laboriosam culpa eum, eaque aliquid quae consectetur!
            Accusantium dicta quos porro explicabo harum molestiae dignissimos nemo quasi perferendis necessitatibus quisquam totam sint facere possimus debitis voluptatem illo, et officiis quae repudiandae molestias suscipit. Voluptas, vitae. Et, nam.
            Neque quidem voluptatem ea recusandae maiores eaque voluptatum fugiat quo nesciunt perspiciatis tempore eveniet consequuntur, animi eligendi obcaecati iure vitae? Dolor dolorem doloribus eaque aliquid eveniet accusantium vitae eius facere!
            Nemo dolorum, a amet sed dolorem pariatur odit sint eum placeat aliquid vero. Repellat ratione nostrum, distinctio illum ad reiciendis voluptatibus optio quis maxime. Ad nesciunt voluptas totam molestias id.
            Natus distinctio ratione ex maiores, exercitationem iste praesentium itaque. Rerum natus enim facilis necessitatibus incidunt similique sed nostrum suscipit commodi, ducimus dolorem quas, quae id repellendus illum eveniet at! Illum.
            Quae facilis quidem corporis sit ullam eaque quam, quaerat molestias quo culpa nemo ab ipsum modi natus accusamus unde placeat laboriosam cumque. Eos ipsum eligendi assumenda. Similique exercitationem dolore ratione?
            Quibusdam dolorem iusto ad a labore blanditiis hic sequi dolore. Enim tempore delectus, repudiandae corporis repellat corrupti ad perferendis fugit. Eius, quibusdam at quaerat nisi magni reiciendis sed distinctio non.
            Iure in vitae fugiat perspiciatis vero ullam quae tenetur distinctio molestias cupiditate amet facilis dolores, ipsam a quas libero enim, quisquam at unde aut atque! Exercitationem dolor praesentium modi illo.
            Hic similique perspiciatis ea fuga corporis ipsa officia veritatis in quae porro, tempore, eius culpa dignissimos soluta rem odio alias minima aperiam id laborum saepe nisi. Vero earum doloremque sequi.
            Quibusdam optio qui nobis labore voluptatem non, esse ipsam nisi vitae nihil maxime asperiores ex culpa itaque explicabo recusandae modi vero quia cumque assumenda? Maxime harum aperiam enim praesentium quis.
            Eius dolorum excepturi minima? Fuga architecto vitae deleniti sapiente repellendus qui! Modi, voluptate dolor? Praesentium voluptatum neque aliquam ratione optio nobis, enim eos? Repellendus saepe natus vel, necessitatibus temporibus officia?
            Iste aliquam itaque velit voluptates incidunt inventore omnis ducimus, eaque ut saepe quasi perspiciatis maiores! Beatae ipsam eius sunt quis sapiente mollitia quaerat accusantium maxime? Possimus dignissimos praesentium necessitatibus tenetur.
            Vel minima earum culpa perspiciatis ab cum nobis saepe ducimus rerum ratione at, alias sit, odio pariatur officia repellat deleniti enim nostrum accusamus. Earum recusandae sequi magnam corporis, in ipsum!
            Porro ab sunt placeat quisquam distinctio explicabo, magnam perspiciatis odio, dolorem minima vel laudantium quos incidunt quidem mollitia optio dignissimos, neque quae quam maxime voluptates. Labore inventore qui dignissimos? Fuga?
            Voluptatem tempora enim voluptatibus laudantium. Corrupti in error, rem eum quisquam enim ex totam voluptatibus optio maxime ipsum labore nesciunt sit beatae velit quae, architecto eveniet. Doloribus expedita eos fugiat.
            Ducimus maiores iure sapiente ipsa, provident dolores eligendi ea, voluptate, voluptas enim eaque vitae unde. Fuga esse laborum alias! Fugit quisquam maxime praesentium veniam magnam veritatis at. Nisi, adipisci consequuntur?
            Iusto fuga animi dolor hic adipisci ad ex tenetur tempora aperiam cupiditate fugiat et eaque necessitatibus eius perferendis, facilis similique aut dolorum enim, aliquid aspernatur. Blanditiis provident aperiam voluptatibus a.
            Sunt, delectus dolor! Quia aspernatur hic reiciendis in sint suscipit nemo quis est, dolorem minima nesciunt voluptatem perspiciatis eligendi, eaque quos consectetur quisquam minus dolor ut unde fugiat officiis aut.
            Magni eveniet tempora laborum dolorum maiores illo quaerat ut quae, tempore nostrum! Dolorem esse autem quam facere cumque laudantium eligendi cum excepturi fugiat ex voluptatem temporibus, obcaecati numquam sit iure.
            Recusandae, excepturi eos rem hic officiis nesciunt reprehenderit aliquid quos quo facere numquam asperiores, quisquam nihil eaque pariatur non eius voluptatibus! Veritatis nobis sapiente fuga quo nesciunt, ipsam mollitia cupiditate.
            Fuga sequi illo voluptate temporibus! Exercitationem libero facilis deserunt expedita, rem laborum? Voluptas vero aut ducimus, deleniti pariatur distinctio officiis! Doloribus repellendus voluptate possimus unde placeat ducimus corporis accusamus iste?
            Eaque officia eos nesciunt atque, rerum voluptates voluptas odit eum quos fugit labore itaque impedit aliquid nihil blanditiis dolorem repellendus quas, a, architecto suscipit! Odit temporibus quasi fuga ad itaque!
            Velit odio optio voluptatibus, voluptatum repudiandae inventore rerum nisi deserunt architecto tenetur error ipsam accusantium fugit laborum doloribus autem distinctio dolores ratione minima asperiores debitis atque iste. Possimus, a laboriosam.
            Adipisci, tempore dolorem maxime provident minima neque, ratione reiciendis voluptatum consequatur nisi ullam sint assumenda, similique id. Optio nam magni minus, a quisquam saepe laudantium dolore omnis corrupti adipisci amet?
            Non provident, minima illo quod et omnis fuga? Illum repellendus excepturi libero autem nostrum inventore dolore voluptates omnis porro! Est quaerat ipsam maxime molestias autem nemo corrupti deserunt, aperiam magni.
        </div>
    </div>
  )
}
